# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\E0010_Piedra Papel o Tijera.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(400, 300)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutMain = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayoutMain.setObjectName("verticalLayoutMain")
        self.horizontalLayoutTop = QtWidgets.QHBoxLayout()
        self.horizontalLayoutTop.setObjectName("horizontalLayoutTop")
        self.label_izquierda = QtWidgets.QLabel(self.centralwidget)
        self.label_izquierda.setStyleSheet("font-size: 14px; font-weight: bold; color: #2E86C1;")
        self.label_izquierda.setText("")
        self.label_izquierda.setPixmap(QtGui.QPixmap(":/Logos/logouat2.jpg"))
        self.label_izquierda.setScaledContents(True)
        self.label_izquierda.setAlignment(QtCore.Qt.AlignLeading)
        self.label_izquierda.setMinimumSize(QtCore.QSize(100, 100))
        self.label_izquierda.setMaximumSize(QtCore.QSize(100, 100))
        self.label_izquierda.setObjectName("label_izquierda")
        self.horizontalLayoutTop.addWidget(self.label_izquierda)
        self.label_derecha = QtWidgets.QLabel(self.centralwidget)
        self.label_derecha.setStyleSheet("font-size: 14px; font-weight: bold; color: #2E86C1;")
        self.label_derecha.setText("")
        self.label_derecha.setPixmap(QtGui.QPixmap(":/Logos/logouat.jpg"))
        self.label_derecha.setScaledContents(True)
        self.label_derecha.setAlignment(QtCore.Qt.AlignRight)
        self.label_derecha.setMinimumSize(QtCore.QSize(100, 100))
        self.label_derecha.setMaximumSize(QtCore.QSize(100, 100))
        self.label_derecha.setObjectName("label_derecha")
        self.horizontalLayoutTop.addWidget(self.label_derecha)
        self.verticalLayoutMain.addLayout(self.horizontalLayoutTop)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setStyleSheet("font-size: 18px; font-weight: bold; color: #2E86C1;")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayoutMain.addWidget(self.label)
        self.boton_piedra = QtWidgets.QPushButton(self.centralwidget)
        self.boton_piedra.setStyleSheet("background-color: #2E86C1; color: white; padding: 15px; border-radius: 10px; font-size: 14px; font-weight: bold;")
        self.boton_piedra.setObjectName("boton_piedra")
        self.verticalLayoutMain.addWidget(self.boton_piedra)
        self.boton_papel = QtWidgets.QPushButton(self.centralwidget)
        self.boton_papel.setStyleSheet("background-color: #1E8449; color: white; padding: 15px; border-radius: 10px; font-size: 14px; font-weight: bold;")
        self.boton_papel.setObjectName("boton_papel")
        self.verticalLayoutMain.addWidget(self.boton_papel)
        self.boton_tijeras = QtWidgets.QPushButton(self.centralwidget)
        self.boton_tijeras.setStyleSheet("background-color: #D35400; color: white; padding: 15px; border-radius: 10px; font-size: 14px; font-weight: bold;")
        self.boton_tijeras.setObjectName("boton_tijeras")
        self.verticalLayoutMain.addWidget(self.boton_tijeras)
        self.label_resultado = QtWidgets.QLabel(self.centralwidget)
        self.label_resultado.setStyleSheet("font-size: 16px; color: #2E86C1; font-weight: bold;")
        self.label_resultado.setText("")
        self.label_resultado.setAlignment(QtCore.Qt.AlignCenter)
        self.label_resultado.setObjectName("label_resultado")
        self.verticalLayoutMain.addWidget(self.label_resultado)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Piedra, Papel, Tijeras"))
        self.label.setText(_translate("MainWindow", "Elige una opción:"))
        self.boton_piedra.setText(_translate("MainWindow", "Piedra"))
        self.boton_papel.setText(_translate("MainWindow", "Papel"))
        self.boton_tijeras.setText(_translate("MainWindow", "Tijeras"))
import recursos_rc
