# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\E007_TeoremadePitagoras.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(455, 424)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_titulo = QtWidgets.QHBoxLayout()
        self.horizontalLayout_titulo.setObjectName("horizontalLayout_titulo")
        self.label_izquierda = QtWidgets.QLabel(self.centralwidget)
        self.label_izquierda.setMinimumSize(QtCore.QSize(80, 80))
        self.label_izquierda.setMaximumSize(QtCore.QSize(100, 100))
        self.label_izquierda.setPixmap(QtGui.QPixmap(":/Logos/logouat2.jpg"))
        self.label_izquierda.setScaledContents(True)
        self.label_izquierda.setAlignment(QtCore.Qt.AlignCenter)
        self.label_izquierda.setObjectName("label_izquierda")
        self.horizontalLayout_titulo.addWidget(self.label_izquierda)
        self.label_titulo = QtWidgets.QLabel(self.centralwidget)
        self.label_titulo.setMinimumSize(QtCore.QSize(300, 40))
        self.label_titulo.setMaximumSize(QtCore.QSize(350, 50))
        self.label_titulo.setStyleSheet("font-size: 18px; font-weight: bold; color: #2E86C1;")
        self.label_titulo.setAlignment(QtCore.Qt.AlignCenter)
        self.label_titulo.setObjectName("label_titulo")
        self.horizontalLayout_titulo.addWidget(self.label_titulo)
        self.label_derecha = QtWidgets.QLabel(self.centralwidget)
        self.label_derecha.setMinimumSize(QtCore.QSize(80, 80))
        self.label_derecha.setMaximumSize(QtCore.QSize(100, 100))
        self.label_derecha.setPixmap(QtGui.QPixmap(":/Logos/logouat.jpg"))
        self.label_derecha.setScaledContents(True)
        self.label_derecha.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.label_derecha.setObjectName("label_derecha")
        self.horizontalLayout_titulo.addWidget(self.label_derecha)
        self.verticalLayout.addLayout(self.horizontalLayout_titulo)
        self.input_cateto1 = QtWidgets.QLineEdit(self.centralwidget)
        self.input_cateto1.setStyleSheet("background-color: #EAFAF1; color: #1E8449; padding: 5px; border: 1px solid #1E8449; border-radius: 5px;")
        self.input_cateto1.setObjectName("input_cateto1")
        self.verticalLayout.addWidget(self.input_cateto1)
        self.input_cateto2 = QtWidgets.QLineEdit(self.centralwidget)
        self.input_cateto2.setStyleSheet("background-color: #EAFAF1; color: #1E8449; padding: 5px; border: 1px solid #1E8449; border-radius: 5px;")
        self.input_cateto2.setObjectName("input_cateto2")
        self.verticalLayout.addWidget(self.input_cateto2)
        self.button_calcular = QtWidgets.QPushButton(self.centralwidget)
        self.button_calcular.setStyleSheet("background-color: #2E86C1; color: white; padding: 10px; border-radius: 5px; font-weight: bold;")
        self.button_calcular.setObjectName("button_calcular")
        self.verticalLayout.addWidget(self.button_calcular)
        self.label_resultado = QtWidgets.QLabel(self.centralwidget)
        self.label_resultado.setStyleSheet("font-size: 14px; color: #1E8449;")
        self.label_resultado.setAlignment(QtCore.Qt.AlignCenter)
        self.label_resultado.setObjectName("label_resultado")
        self.verticalLayout.addWidget(self.label_resultado)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 455, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Teorema de Pitágoras"))
        self.label_titulo.setText(_translate("MainWindow", "Teorema de Pitágoras"))
        self.input_cateto1.setPlaceholderText(_translate("MainWindow", "Cateto 1"))
        self.input_cateto2.setPlaceholderText(_translate("MainWindow", "Cateto 2"))
        self.button_calcular.setText(_translate("MainWindow", "Calcular"))
        self.label_resultado.setText(_translate("MainWindow", "Resultado:"))
import recursos_rc
