# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\E008_TabladeMultiplicar.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(400, 350)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_top = QtWidgets.QHBoxLayout()
        self.horizontalLayout_top.setObjectName("horizontalLayout_top")
        self.label_izquierda = QtWidgets.QLabel(self.centralwidget)
        self.label_izquierda.setStyleSheet("font-size: 14px; color: #2E86C1;")
        self.label_izquierda.setText("")
        self.label_izquierda.setPixmap(QtGui.QPixmap(":/Logos/logouat2.jpg"))
        self.label_izquierda.setScaledContents(True)
        self.label_izquierda.setAlignment(QtCore.Qt.AlignCenter)
        self.label_izquierda.setMinimumSize(QtCore.QSize(100, 100))
        self.label_izquierda.setObjectName("label_izquierda")
        self.horizontalLayout_top.addWidget(self.label_izquierda)
        self.label_derecha = QtWidgets.QLabel(self.centralwidget)
        self.label_derecha.setStyleSheet("font-size: 14px; color: #2E86C1;")
        self.label_derecha.setText("")
        self.label_derecha.setPixmap(QtGui.QPixmap(":/Logos/logouat.jpg"))
        self.label_derecha.setScaledContents(True)
        self.label_derecha.setAlignment(QtCore.Qt.AlignCenter)
        self.label_derecha.setMinimumSize(QtCore.QSize(100, 100))
        self.label_derecha.setObjectName("label_derecha")
        self.horizontalLayout_top.addWidget(self.label_derecha)
        self.verticalLayout.addLayout(self.horizontalLayout_top)
        self.label_titulo = QtWidgets.QLabel(self.centralwidget)
        self.label_titulo.setStyleSheet("font-size: 18px; font-weight: bold; color: #2E86C1;")
        self.label_titulo.setAlignment(QtCore.Qt.AlignCenter)
        self.label_titulo.setObjectName("label_titulo")
        self.verticalLayout.addWidget(self.label_titulo)
        self.input_numero = QtWidgets.QLineEdit(self.centralwidget)
        self.input_numero.setStyleSheet("background-color: #EAFAF1; color: #1E8449; padding: 5px; border: 1px solid #1E8449; border-radius: 5px;")
        self.input_numero.setObjectName("input_numero")
        self.verticalLayout.addWidget(self.input_numero)
        self.button_calcular = QtWidgets.QPushButton(self.centralwidget)
        self.button_calcular.setStyleSheet("background-color: #2E86C1; color: white; padding: 10px; border-radius: 5px; font-weight: bold;")
        self.button_calcular.setObjectName("button_calcular")
        self.verticalLayout.addWidget(self.button_calcular)
        self.text_resultado = QtWidgets.QTextEdit(self.centralwidget)
        self.text_resultado.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.text_resultado.sizePolicy().hasHeightForWidth())
        self.text_resultado.setSizePolicy(sizePolicy)
        self.text_resultado.setMinimumSize(QtCore.QSize(0, 120))
        self.text_resultado.setStyleSheet("background-color: #EAFAF1; color: #1E8449; padding: 10px; border: 1px solid #1E8449; border-radius: 5px; font-size: 14px;")
        self.text_resultado.setReadOnly(True)
        self.text_resultado.setObjectName("text_resultado")
        self.verticalLayout.addWidget(self.text_resultado)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 400, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Tabla de Multiplicar"))
        self.label_titulo.setText(_translate("MainWindow", "Tabla de Multiplicar"))
        self.input_numero.setPlaceholderText(_translate("MainWindow", "Ingrese un número"))
        self.button_calcular.setText(_translate("MainWindow", "Calcular"))
import recursos_rc
