# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\E009_AdivinaelNumero.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(400, 300)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.topLayout = QtWidgets.QHBoxLayout()
        self.topLayout.setObjectName("topLayout")
        self.label_esquina_izquierda = QtWidgets.QLabel(self.centralwidget)
        self.label_esquina_izquierda.setText("")
        self.label_esquina_izquierda.setPixmap(QtGui.QPixmap(":/Logos/logouat2.jpg"))
        self.label_esquina_izquierda.setScaledContents(True)
        self.label_esquina_izquierda.setMinimumSize(QtCore.QSize(100, 100))
        self.label_esquina_izquierda.setMaximumSize(QtCore.QSize(100, 100))
        self.label_esquina_izquierda.setObjectName("label_esquina_izquierda")
        self.topLayout.addWidget(self.label_esquina_izquierda)
        self.label_esquina_derecha = QtWidgets.QLabel(self.centralwidget)
        self.label_esquina_derecha.setText("")
        self.label_esquina_derecha.setPixmap(QtGui.QPixmap(":/Logos/logouat.jpg"))
        self.label_esquina_derecha.setScaledContents(True)
        self.label_esquina_derecha.setMinimumSize(QtCore.QSize(100, 100))
        self.label_esquina_derecha.setMaximumSize(QtCore.QSize(100, 100))
        self.label_esquina_derecha.setObjectName("label_esquina_derecha")
        self.topLayout.addWidget(self.label_esquina_derecha)
        self.verticalLayout.addLayout(self.topLayout)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setEnabled(True)
        self.label.setStyleSheet("font-size: 16px; font-weight: bold; color: #2E86C1;")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.input_numero = QtWidgets.QLineEdit(self.centralwidget)
        self.input_numero.setStyleSheet("background-color: #EAFAF1; color: #1E8449; padding: 10px; border: 2px solid #1E8449; border-radius: 10px; font-size: 14px;")
        self.input_numero.setAlignment(QtCore.Qt.AlignCenter)
        self.input_numero.setObjectName("input_numero")
        self.verticalLayout.addWidget(self.input_numero)
        self.boton_adivinar = QtWidgets.QPushButton(self.centralwidget)
        self.boton_adivinar.setStyleSheet("background-color: #2E86C1; color: white; padding: 10px; border-radius: 10px; font-size: 14px; font-weight: bold;")
        self.boton_adivinar.setObjectName("boton_adivinar")
        self.verticalLayout.addWidget(self.boton_adivinar)
        self.label_resultado = QtWidgets.QLabel(self.centralwidget)
        self.label_resultado.setStyleSheet("font-size: 14px; color: #1E8449; font-weight: bold;")
        self.label_resultado.setText("")
        self.label_resultado.setAlignment(QtCore.Qt.AlignCenter)
        self.label_resultado.setObjectName("label_resultado")
        self.verticalLayout.addWidget(self.label_resultado)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Adivina el número"))
        self.label.setText(_translate("MainWindow", "Adivina el número (entre 1 y 100):"))
        self.boton_adivinar.setText(_translate("MainWindow", "Adivinar"))
import recursos_rc
