# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\E01_Grados_a_Fahrenheit.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1116, 779)
        MainWindow.setStyleSheet("background-color: rgb(239, 159, 119);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.dial = QtWidgets.QDial(self.centralwidget)
        self.dial.setGeometry(QtCore.QRect(190, 250, 241, 281))
        self.dial.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 255, 255);")
        self.dial.setObjectName("dial")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(460, 250, 361, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.txt_grados = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_grados.setGeometry(QtCore.QRect(460, 300, 321, 61))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.txt_grados.setFont(font)
        self.txt_grados.setStyleSheet("border-radius: 15px;\n"
"background-color: rgb(255, 255, 255);\n"
"border:  5px solid black;\n"
"")
        self.txt_grados.setText("")
        self.txt_grados.setAlignment(QtCore.Qt.AlignCenter)
        self.txt_grados.setObjectName("txt_grados")
        self.txt_fahrenheit = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_fahrenheit.setGeometry(QtCore.QRect(460, 430, 321, 61))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.txt_fahrenheit.setFont(font)
        self.txt_fahrenheit.setStyleSheet("border-radius: 15px;\n"
"background-color: rgb(255, 255, 255);\n"
"border:  5px solid black;\n"
"")
        self.txt_fahrenheit.setText("")
        self.txt_fahrenheit.setAlignment(QtCore.Qt.AlignCenter)
        self.txt_fahrenheit.setObjectName("txt_fahrenheit")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(460, 380, 341, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(830, 0, 271, 211))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap(":/Ejercicios/logouat.jpg"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(30, 0, 201, 211))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap(":/Ejercicios/logouat2.jpg"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(840, 550, 251, 191))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap(":/Ejercicios/gatoinplorandoayuda.jpg"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1116, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "GRADOS CENTIGRADOS C °:"))
        self.label_3.setText(_translate("MainWindow", "GRADOS FAHRENHEIT F °:"))
import recursos_rc
