# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\E05_Peso_a_Dolar.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1116, 810)
        MainWindow.setStyleSheet("background-color: rgb(0, 85, 0)")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.dial = QtWidgets.QDial(self.centralwidget)
        self.dial.setGeometry(QtCore.QRect(230, 240, 241, 281))
        self.dial.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 255, 255);")
        self.dial.setObjectName("dial")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(460, 250, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.txt_metros = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_metros.setGeometry(QtCore.QRect(490, 290, 321, 61))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.txt_metros.setFont(font)
        self.txt_metros.setStyleSheet("border-radius: 15px;\n"
"background-color: rgb(255, 255, 255);\n"
"border:  5px solid black;\n"
"")
        self.txt_metros.setText("")
        self.txt_metros.setAlignment(QtCore.Qt.AlignCenter)
        self.txt_metros.setObjectName("txt_metros")
        self.txt_kms = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_kms.setGeometry(QtCore.QRect(490, 420, 321, 61))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.txt_kms.setFont(font)
        self.txt_kms.setStyleSheet("border-radius: 15px;\n"
"background-color: rgb(255, 255, 255);\n"
"border:  5px solid black;\n"
"")
        self.txt_kms.setText("")
        self.txt_kms.setAlignment(QtCore.Qt.AlignCenter)
        self.txt_kms.setObjectName("txt_kms")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(450, 380, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(840, 560, 251, 191))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap(":/Ejercicios/gatoinplorandoayuda.jpg"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(830, 0, 271, 211))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap(":/Ejercicios/logouat.jpg"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(10, -20, 201, 211))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap(":/Ejercicios/logouat2.jpg"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1116, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "PESOS:"))
        self.label_3.setText(_translate("MainWindow", "DOLARES"))
import recursos_rc
