# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\E06_Area_Pentagono.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1116, 810)
        MainWindow.setStyleSheet("background-color: rgb(85, 85, 255)")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(300, 200, 401, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.txt_metros = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_metros.setGeometry(QtCore.QRect(320, 250, 361, 61))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.txt_metros.setFont(font)
        self.txt_metros.setStyleSheet("border-radius: 15px;\n"
"background-color: rgb(255, 255, 255);\n"
"border:  5px solid black;\n"
"")
        self.txt_metros.setText("")
        self.txt_metros.setAlignment(QtCore.Qt.AlignCenter)
        self.txt_metros.setObjectName("txt_metros")
        self.txt_apotema = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_apotema.setGeometry(QtCore.QRect(320, 380, 361, 61))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.txt_apotema.setFont(font)
        self.txt_apotema.setStyleSheet("border-radius: 15px;\n"
"background-color: rgb(255, 255, 255);\n"
"border:  5px solid black;\n"
"")
        self.txt_apotema.setText("")
        self.txt_apotema.setAlignment(QtCore.Qt.AlignCenter)
        self.txt_apotema.setObjectName("txt_apotema")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(330, 340, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(840, 560, 251, 191))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap(":/Ejercicios/gatoinplorandoayuda.jpg"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(830, 0, 271, 211))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap(":/Ejercicios/logouat.jpg"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(10, -20, 201, 211))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap(":/Ejercicios/logouat2.jpg"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(290, 470, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.txt_resultado = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_resultado.setGeometry(QtCore.QRect(320, 510, 361, 61))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.txt_resultado.setFont(font)
        self.txt_resultado.setStyleSheet("border-radius: 15px;\n"
"background-color: rgb(255, 255, 255);\n"
"border:  5px solid black;\n"
"")
        self.txt_resultado.setText("")
        self.txt_resultado.setAlignment(QtCore.Qt.AlignCenter)
        self.txt_resultado.setObjectName("txt_resultado")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1116, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Ingresa longitud del lado L"))
        self.label_3.setText(_translate("MainWindow", "Ingresa Apotema"))
        self.label_6.setText(_translate("MainWindow", "Resultado:"))
import recursos_rc
